//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticeStudy.Components
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentByProduct
    {
        public int Id { get; set; }
        public int ProductOrderId { get; set; }
    
        public virtual ProductOrder ProductOrder { get; set; }
    }
}
