//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticeStudy.Components
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductShipment
    {
        public int Id { get; set; }
        public int ProductId { get; set; }
        public int ShipmentId { get; set; }
        public Nullable<int> PurchasePrice { get; set; }
        public Nullable<int> Quantity { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Shipment Shipment { get; set; }
    }
}
